/**
 * Migration 1: the first relational schema.
 *
 * Conventions
 * - Names are snake_case. Primary keys are TEXT ids generated by the app (UUIDs).
 * - Timestamps are UTC ISO-8601 strings exactly as Date.prototype.toISOString()
 *   produces them, so they sort correctly as text.
 * - Booleans are INTEGER 0 or 1.
 * - Tables are STRICT: a value of the wrong type is rejected instead of coerced.
 * - There are no soft-delete, archive, tombstone, or synchronization columns.
 *   Deleting means a physical DELETE.
 *
 * Deletion policy, enforced by the foreign keys below
 * - CASCADE only inside an aggregate, where the child cannot exist on its own:
 *     exam   -> exam_questions -> answer_keys
 *     result -> student_answers, scan_records
 * - RESTRICT wherever a delete would otherwise take a separate collection of
 *   the Teacher's records with it:
 *     class   cannot be deleted while it has students or exams
 *     subject cannot be deleted while it has exams
 *     student cannot be deleted while it has results
 *     exam    cannot be deleted while it has results
 *   A use case that is meant to remove such a parent together with its results
 *   must delete those results explicitly, in the same transaction, after the
 *   Teacher has confirmed what will be removed. The database never does it
 *   silently.
 *
 * Scan images
 * - scan_records.image_path is only a path to a file in the app's local
 *   storage. SQLite cannot delete files, and a CASCADE that removes a
 *   scan_records row would lose the path. The result-deletion use case must:
 *     1. read image_path for the result (and for every result it will remove),
 *     2. delete the rows in one transaction,
 *     3. delete the files only after that transaction commits.
 *   This is one more reason results are never removed by a cascade from an
 *   exam or a student.
 */

const ID = `TEXT PRIMARY KEY NOT NULL CHECK (length(id) > 0)`;

const ISO_UTC =
  `'[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T` +
  `[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]Z'`;

const timestamp = (column: string) => `${column} TEXT NOT NULL CHECK (${column} GLOB ${ISO_UTC})`;

// The standardized answer sheet has four bubbles per question: A, B, C, D.
const ANSWER_LETTERS = `('A', 'B', 'C', 'D')`;

export const INITIAL_SCHEMA_SQL = `
CREATE TABLE subjects (
  id ${ID},
  name TEXT NOT NULL COLLATE NOCASE CHECK (length(trim(name)) > 0),
  ${timestamp('created_at')},
  ${timestamp('updated_at')},
  UNIQUE (name)
) STRICT;

CREATE TABLE classes (
  id ${ID},
  name TEXT NOT NULL COLLATE NOCASE CHECK (length(trim(name)) > 0),
  ${timestamp('created_at')},
  ${timestamp('updated_at')},
  UNIQUE (name)
) STRICT;

CREATE TABLE students (
  id ${ID},
  class_id TEXT NOT NULL REFERENCES classes (id) ON DELETE RESTRICT,
  student_number TEXT NOT NULL CHECK (length(trim(student_number)) > 0),
  full_name TEXT NOT NULL CHECK (length(trim(full_name)) > 0),
  ${timestamp('created_at')},
  ${timestamp('updated_at')},
  UNIQUE (class_id, student_number)
) STRICT;

CREATE INDEX idx_students_class_id_full_name ON students (class_id, full_name);

CREATE TABLE exams (
  id ${ID},
  subject_id TEXT NOT NULL REFERENCES subjects (id) ON DELETE RESTRICT,
  class_id TEXT NOT NULL REFERENCES classes (id) ON DELETE RESTRICT,
  title TEXT NOT NULL CHECK (length(trim(title)) > 0),
  question_count INTEGER NOT NULL CHECK (question_count >= 1),
  ${timestamp('created_at')},
  ${timestamp('updated_at')}
) STRICT;

CREATE INDEX idx_exams_subject_id ON exams (subject_id);
CREATE INDEX idx_exams_class_id ON exams (class_id);
CREATE INDEX idx_exams_created_at ON exams (created_at);

CREATE TABLE exam_questions (
  id ${ID},
  exam_id TEXT NOT NULL REFERENCES exams (id) ON DELETE CASCADE,
  question_number INTEGER NOT NULL CHECK (question_number >= 1),
  choice_count INTEGER NOT NULL DEFAULT 4 CHECK (choice_count BETWEEN 2 AND 4),
  points INTEGER NOT NULL DEFAULT 1 CHECK (points >= 1),
  UNIQUE (exam_id, question_number)
) STRICT;

CREATE TABLE answer_keys (
  id ${ID},
  exam_question_id TEXT NOT NULL REFERENCES exam_questions (id) ON DELETE CASCADE,
  correct_answer TEXT NOT NULL CHECK (correct_answer IN ${ANSWER_LETTERS}),
  UNIQUE (exam_question_id)
) STRICT;

CREATE TABLE exam_results (
  id ${ID},
  exam_id TEXT NOT NULL REFERENCES exams (id) ON DELETE RESTRICT,
  student_id TEXT NOT NULL REFERENCES students (id) ON DELETE RESTRICT,
  score INTEGER NOT NULL CHECK (score >= 0),
  total INTEGER NOT NULL CHECK (total >= 0),
  ${timestamp('created_at')},
  CHECK (score <= total)
) STRICT;

-- One saved result per student per exam. A separate index rather than a table
-- constraint so a later migration can drop it if retakes are ever allowed.
CREATE UNIQUE INDEX idx_exam_results_exam_id_student_id ON exam_results (exam_id, student_id);
CREATE INDEX idx_exam_results_student_id ON exam_results (student_id);
CREATE INDEX idx_exam_results_created_at ON exam_results (created_at);

CREATE TABLE student_answers (
  id ${ID},
  result_id TEXT NOT NULL REFERENCES exam_results (id) ON DELETE CASCADE,
  question_number INTEGER NOT NULL CHECK (question_number >= 1),
  state TEXT NOT NULL CHECK (state IN ('SELECTED', 'BLANK', 'MULTIPLE', 'UNCERTAIN')),
  selected_answer TEXT CHECK (selected_answer IN ${ANSWER_LETTERS}),
  is_correct INTEGER NOT NULL CHECK (is_correct IN (0, 1)),
  teacher_corrected INTEGER NOT NULL DEFAULT 0 CHECK (teacher_corrected IN (0, 1)),
  UNIQUE (result_id, question_number),
  -- An answer letter is recorded exactly when one bubble was read as selected.
  CHECK ((state = 'SELECTED') = (selected_answer IS NOT NULL))
) STRICT;

CREATE TABLE scan_records (
  id ${ID},
  result_id TEXT NOT NULL REFERENCES exam_results (id) ON DELETE CASCADE,
  -- Path of the scan image in local storage, or NULL when no image was kept.
  image_path TEXT CHECK (image_path IS NULL OR length(image_path) > 0),
  ${timestamp('scanned_at')},
  UNIQUE (result_id)
) STRICT;
`;
